Fakebook/Models/Thread.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fakebook.Models
{
    public class Thread
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int IdCategory { get; set; }
        public string Description { get; set; }
        public DateTime Created { get; set; } = DateTime.Now;


        /// <summary>
        /// Retorna el nombre de la categoria en base al IdCategory y la lista de categorias
        /// </summary>
        /// <param name="_idCategory"></param>
        /// <param name="_categorias"></param>
        /// <returns></returns>
        public string GetNameCategory(int _idCategory,List<Category> _categorias)
        {
           return _categorias.First(x => x.Id == _idCategory).Name;
        }
    }
    
}

Fakebook/Controllers/CommentController.cs
using Fakebook.Context;
using Fakebook.Models;
using Fakebook.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fakebook.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddComment(DetailThread _detailThread)
        {
            using (FakebookContext Fk = new FakebookContext())
            {
                _detailThread.Comment.IdThread = _detailThread.Thread.Id;
                Fk.Comments.Add(_detailThread.Comment);
                Fk.SaveChanges();
                return RedirectToAction("Detail", "Thread",new{_id = _detailThread.Thread.Id });
            }

        }
    }
}

Fakebook/Controllers/ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fakebook.Context;
using Fakebook.Models;
using Fakebook.ViewModels;

namespace Fakebook.Controllers
{
    public class ThreadController : Controller
    {
        // GET: Thread
        public ActionResult Index()
        {
            using (FakebookContext Fk = new FakebookContext()) {
                Home content = new Home(Fk.Threads.ToList(),Fk.Categories.ToList());              
                return View(content);
            }
          
        }

        public ActionResult Create()
        {
            ViewBag.State = "Nueva Recomendación";
            using (FakebookContext Fk = new FakebookContext())
            {
                //Creamos una instancia de un nuevo post
                Thread newThread = new Thread();
                //creamos la instancia del nuevo modelo para alta de post
                ThreadCRU AddThread = new ThreadCRU(Fk.Categories.ToList());
                //compactamos las dos instancias para poder complementar vista y modelo
                AddThread.Thread = newThread;
                return View(AddThread);
            }

        }

        public ActionResult Edit(int _id)
        {
            ViewBag.State = "Editar Recomendación";
            using (FakebookContext Fk = new FakebookContext())
            {
                //Creamos una instancia de un post para colocar nuesto elemnto editado
                Thread editThread = Fk.Threads.First(x => x.Id == _id);
                //creamos la instancia del nuevo modelo para alta de post
                ThreadCRU threadCRU = new ThreadCRU(Fk.Categories.ToList());
                //compactamos las dos instancias para poder complementar vista y modelo
                threadCRU.Thread = editThread;
                return View("Create",threadCRU);
            }

        }

        [HttpPost]
        public ActionResult AddOrEdit(ThreadCRU _threadCRUD)
        {
            Thread _thread = _threadCRUD.Thread;
            using (FakebookContext Fk = new FakebookContext())
            {
                if (Fk.Threads.Any(x => x.Id == _thread.Id))
                {
                    Thread threadEdit = Fk.Threads.First(x => x.Id == _thread.Id);
                    threadEdit.Title = _thread.Title;
                    threadEdit.Description = _thread.Description;
                    threadEdit.IdCategory = _thread.IdCategory;
                    Fk.SaveChanges();

                }
                else
                {
                    Fk.Threads.Add(_thread);
                    Fk.SaveChanges();
                }

                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int _id)
        {
            using (FakebookContext Fk= new FakebookContext())
            {
                Thread thread= Fk.Threads.First(x=> x.Id == _id);
                return View(thread);
            }
        }

        [HttpPost]
        public ActionResult Delete(Thread _thread)
        {
            using (FakebookContext Fk = new FakebookContext())
            {
                Thread thread = Fk.Threads.First(x => x.Id == _thread.Id);
                Fk.Threads.Remove(thread);
                Fk.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Detail(int _id)
        {
            //consultamos en base al Id 
            using (FakebookContext Fk = new FakebookContext())
            {
                Thread threadConsultado = Fk.Threads.First(x=> x.Id == _id);
                Comment comment = new Comment();


                DetailThread detail = new DetailThread
                (
                    Fk.Categories.ToList()
                   ,Fk.Comments.Where(x=>x.IdThread== _id).ToList()
                   ,threadConsultado
                   ,comment
                );
                return View(detail);

            }

            

        }

    }
}

Fakebook/Views/Thread/Create.cshtml
@model Fakebook.ViewModels.ThreadCRU
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.State</h2>

<div class="container">
@using (Html.BeginForm("AddOrEdit", "Thread"))
{
    <!--Ocultamos el Id-->
    @Html.HiddenFor(model => model.Thread.Id)
    <div class="form-group">
        @Html.Label("Canción")
        @Html.TextBoxFor(model => model.Thread.Title, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Genero")
        @Html.DropDownListFor(model => model.Thread.IdCategory, new SelectList(Model.Categories, "Id", "Name"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("¿Que sentiste?")
        @Html.TextAreaFor(model => model.Thread.Description, new { @class = "form-control" })
     </div>
        <input class="btn-success" type="submit" value="Guardar" />
}
</div>

Fakebook/Views/Thread/Delete.cshtml
@model Fakebook.Models.Thread
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Eliminar</h2>
    @using (Html.BeginForm("Delete", "Thread"))
    {
        @Html.HiddenFor(m => m.Id)
      

        <div class="form-group">
            <p>
                Está seguro que desea eliminar el post ID: @Model.Id ?
            </p>
        </div>

        <p>
            @Html.ActionLink("Cancelar", "Index")
            <input type="submit" class="btn-danger" value="Sí :'v'" />
        </p>
    }
</div>

Fakebook/Views/Thread/Detail.cshtml
@model Fakebook.ViewModels.DetailThread
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Recomendación ID: @Model.Thread.Id</h2>

<div class="container">
    <div class="row">
        @Html.Label(Model.Thread.Title)<br />
        @Html.Label(Model.Thread.Description)<br />


        @Html.Label(Model.Thread.Created.ToString("dd/MM/yyyy"))
    </div>
    <br />
    <div class="row">
        @using (Html.BeginForm("AddComment", "Comment"))
        {
            <div class="form-group">
                @Html.Label("Nombre")
                @Html.TextBoxFor(modelo => modelo.Comment.Author, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("Comentario")
                @Html.TextAreaFor(modelo => modelo.Comment.CommentText, new { @class = "form-control" })
            </div>
            @Html.HiddenFor(modelo=>modelo.Thread.Id)
            <input class="btn-success" type="submit" value="Comentar" />
        }
               
    </div>
    <br />
    <div class="row">
        <h1>Comentarios</h1><br />
        @foreach (Fakebook.Models.Comment comment in Model.Comments)
        {
            <div class="form-group">
                <pre>
                @Html.Label(comment.Author,new { style = "color:blue;" })
                <br>
                @Html.Label(comment.CommentText)
                </pre>
                
            </div>            

        }
    </div>
</div>

Fakebook/Views/Thread/Index.cshtml
@model Fakebook.ViewModels.Home
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2>Canciónes Recomendadas</h2>
        <div class="pull-right">
            @Html.ActionLink("Nueva Recomendación", "Create", new { }, new { @class = "glyphicon glyphicon-plus" })
        </div>
    </div>
    
    
    <hr class="hr-custom"/>
    @foreach (Fakebook.Models.Thread thread in Model.Threads)
    {
        <div class="form-group">
            <div>
                @Html.ActionLink(thread.Title, "Detail", new { _id = thread.Id } ,new{@class= "title-song"})
                
                <br />
                @Html.Label("Genero:")
                @Html.Label(thread.GetNameCategory(thread.IdCategory, Model.Categories), new { style = "color:#8A2BE2;" })
                <br />
                @Html.Label("Fecha recomendación:")
                @Html.Label(thread.Created.ToString("dd/MM/yyyy"))
            </div>
            <div >
                @Html.ActionLink("Editar", "Edit", new { _id = thread.Id },new {@class= "glyphicon glyphicon-edit" })
                @Html.ActionLink("Eliminar", "Delete", new { _id = thread.Id }, new { @class = "glyphicon glyphicon-trash" })
            </div>
        </div>
        <hr class="hr-custom" />

    }

</div>